services:
  - type: web
    name: wrapper-backend
    env: python
    region: frankfurt
    plan: free
    branch: main
    runtime: python
    pythonVersion: 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 10000
